# CompanyOS Backend Bundle Routes - Catch All für Vue.js SPA
companyos_backend:
    path: /{route}
    controller: CompanyOS\BackendBundle\Controller\BackendController::index
    requirements:
        route: .*
    defaults:
        route: '' 