# CompanyOS Backend Bundle Routes - Catch All für Vue.js SPA
company_os_backend:
    path: /{route}
    controller: CompanyOS\Bundle\BackendBundle\Controller\BackendController::index
    requirements:
        route: .*
    defaults:
        route: '' 