company_os_backend:
    path: /admin/{route}
    controller: CompanyOSBackend\Controller\BackendController::index
    methods: [GET]
    # allow `route` to match literally anything (including slashes)
    requirements:
        route: ".*"
    # make `route` optional so `/admin` also matches
    defaults:
        route: ""