services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    CompanyOS\Bundle\BackendBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Security Headers Listener
    CompanyOS\Bundle\BackendBundle\EventListener\SecurityHeadersListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response }

    # CSRF Token Manager
    CompanyOS\Bundle\BackendBundle\Controller\BackendController:
        tags:
            - { name: 'controller.service_arguments' }

    CompanyOS\Bundle\BackendBundle\Twig\ViteExtension:
        arguments:
            $buildPath: '/bundles/companyosbackend/build'
            $isDev: '%kernel.debug%'
            $projectDir: '%kernel.project_dir%'
        tags:
            - { name: twig.extension } 