services:
    _defaults:
        autowire: true
        autoconfigure: true

    CompanyOS\BackendBundle\:
        resource: '%kernel.project_dir%/vendor/companyos/backend/src/'
        exclude:
            - '%kernel.project_dir%/vendor/companyos/backend/src/DependencyInjection/'
            - '%kernel.project_dir%/vendor/companyos/backend/src/Resources/' 