services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Security Headers Listener
    CompanyOS\Bundle\BackendBundle\EventListener\SecurityHeadersListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response }

    # CSRF Token Manager
    CompanyOS\Bundle\BackendBundle\Controller\BackendController:
        tags:
            - { name: 'controller.service_arguments' } 