services:
    _defaults:
        autowire: true
        autoconfigure: true

    CompanyOS\BackendBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Resources/' 