services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    CompanyOS\Bundle\BackendBundle\:
        resource: '../../src/'
        exclude:
            - '../../src/DependencyInjection/'
            - '../../src/Tests/'

    # Security Headers Listener
    CompanyOS\Bundle\BackendBundle\EventListener\SecurityHeadersListener:
        arguments:
            $environment: '%kernel.environment%'
        tags:
            - { name: 'kernel.event_subscriber' } 