services:
    _defaults:
        autowire: true
        autoconfigure: true

    CompanyOS\BackendBundle\:
        resource: '%kernel.project_dir%/vendor/companyos/backend-bundle/src/'
        exclude:
            - '%kernel.project_dir%/vendor/companyos/backend-bundle/src/DependencyInjection/'
            - '%kernel.project_dir%/vendor/companyos/backend-bundle/src/Resources/' 